### ISSUE TITLE
Pending request for Method Code update RE: SOR for AI/GOA

### ISSUE THREAD

**Issue by Ned-Laman-NOAA** [afsc-gap-products/trawlmetrics#37]
### Issue

I've submitted a request to Nancy and Chris to add a new method code and definition to the RACE Codes for Net Mensuration. The present Method Code = 7 is written to be specific for the Bering Sea. Here's what I'm proposing to cover the similar method but for the Aleutians and Gulf:

Method Code = 8 (proposed)
Marport with sequential outlier rejection (proposed)

**Comment by sean-rohan-NOAA** [comment]
@ChrisAnderson-NOAA Looping back to this. Has this method code been created for processing the AI net mensuration data?

**Comment by Ned-Laman-NOAA** [comment]
I can imagine that the need for this code may become a little more acute next week when the Aleutians team gets around to running the SOR and Spread/Height estimation code that Sean's provided.
@ChrisAnderson-NOAA let's talk about what you need from me so that we can get this done. I'll be free after 330 or so today

**Comment by ChrisAnderson-NOAA** [comment]
@sean-rohan-NOAA Completed. You now have Code 8; Marport with sequential outlier rejection. Let me know if there are any problems!

**Comment by sean-rohan-NOAA** [comment]
Thanks! I'll incorporate spread code 8 into the package as a method for the GOA and AI.

**Comment by Ned-Laman-NOAA** [comment]
Thank you, Sean and Chris.

**Comment by sean-rohan-NOAA** [comment]
Closed by #41
